### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Hightiz** [Drahsid/XIIHook#37] opened 2020-05-24 01:49 UTC
Probably doing something wrong, but I uploaded a screen shot. I simply ran the exe from my downloads folder when  the game is running and I get a runtime error.

![ttyyuu](https://user-images.githubusercontent.com/65837909/82743867-df65b180-9d36-11ea-9b3d-c24b313890e6.PNG)

**Comment by Drahsid** [comment] 2020-05-24 01:53
You're running on the latest update right? If so, this is a duplicate of #36

**Comment by Hightiz** [comment] 2020-05-24 01:55
I got the latest Update 14 from Nexus.

**Comment by Drahsid** [comment] 2020-05-24 01:56
I'm talking about the latest version of the game.
I have not updated this to support version 1.0.4 of ffxii.

**Comment by Hightiz** [comment] 2020-05-24 02:00
I'm assuming it is updated with the newest patch. Tried using your tool many times and I can't get it to work because of new patches coming out. I simply and only want to adjust the FOV.

**Comment by Hightiz** [comment] 2020-05-24 02:04
I talked to you about this before on Discord, and I guess you updated it for the last patch, but I took too long to come back and use it that another patch dropped lol

**Comment by Drahsid** [comment] 2020-05-24 02:07
I'm not sure if I was unclear, but I have not yet updated this to support the latest patch, so for it to work you either have to predate to 1.0.3 or wait for my next update. Please take a gander at the other issues before posting a duplicate issue. 
If you want to adjust your fov, there are numerous methods out there. If you have a memory editor, at 0x02097548 is a floating point value that represents the field of view in radians. It is 45 degrees by default, which is 0.7853982 rad.

**Closed by Drahsid** 2020-05-24 02:07 UTC
Labels: invalid
